library(ggplot2)
library(plyr)
library(scales)


# Load data generated by ../analyticstestingtwo.py
playlistContents <- read.table('../playlists.txt', sep=',', header=T)
titles <- read.table('../videoIdsAndTitles.txt', sep=',')
colnames(titles) <- c('videoId', 'videoTitle')
viewsOfVideo <- read.table('../datesAndViews.txt', sep=',')

colnames(viewsOfVideo) <- c('videoId', 'date', 'views')
viewsOfVideo$date <- as.Date(viewsOfVideo$date)
viewsOfVideo$year <- substr(viewsOfVideo$date, 1, 4)
viewsOfVideo$month <- substr(viewsOfVideo$date, 6, 7)
viewsOfVideo$day <- substr(viewsOfVideo$date, 9, 10)
viewOnPlaylists <- merge(viewsOfVideo, playlistContents, by='videoId')

# Subset to interesting time period
viewsOfVideo <- subset(viewsOfVideo, viewsOfVideo$date > '2013-08-31')
viewOnPlaylists <- subset(viewOnPlaylists, viewOnPlaylists$date > '2013-08-31')

# Calculate total number of views
totalViewsPerDate <- ddply(viewOnPlaylists, .(date, playlistTitle), summarize, totalViews=sum(views))
viewsPerDate <- ddply(viewOnPlaylists, .(date), summarize, totalViews=sum(views))

# Calculate total number of views per video per month
totalViewsPerVideoPerMonth <- ddply(viewsOfVideo, .(year, month, videoId), summarize, totalViews=sum(views))
titlesViewPerMonth <- merge(totalViewsPerVideoPerMonth, titles, by='videoId')
titlesViewPerMonth$videoTitleShort <- substr(titlesViewPerMonth$videoTitle, 0, 50)
temp <- titlesViewPerMonth[order(-titlesViewPerMonth$totalViews), c('year', 'month', 'totalViews', 'videoTitle', 'videoTitleShort')]
temp[, c('year', 'month', 'totalViews', 'videoTitleShort')]

extractFiveVideosWithMostViews <- function(df)
{
  print(df)
  temp <- df[order(-df$totalViews), c('year', 'month', 'totalViews', 'videoTitleShort')]  
  tempTwo <- head(temp, 5)
  print(tempTwo)
  tempTwo
}
ddply(titlesViewPerMonth, .(year, month), extractFiveVideosWithMostViews)

# General overview of minutes watched on different playlists.
p <- ggplot(totalViewsPerDate) + 
    geom_line(aes(date, totalViews, colour=playlistTitle)) + 
    xlab('Dato') + ylab('Minutter set')
#p
ggsave("plots/01 General overview.pdf", p, width=10, height=6)

# Specific view of fall semester and IFG1 videos
inFallSemester = subset(totalViewsPerDate, 
                        as.Date(totalViewsPerDate$date) > "2012-09-01" &
                          as.Date(totalViewsPerDate$date) < "2013-01-31")
p <- ggplot(subset(inFallSemester, inFallSemester$playlistTitle == 'IFG1 - Introduktion til Matematik og Fysik')) + 
  geom_line(aes(date, totalViews)) + 
  xlab('Dato') + ylab('Minutter set')
#p
ggsave("plots/02 Minutes watched of IFG1 in fall semester 2013.pdf", p)



cumulatedViewsPerDate = ddply(totalViewsPerDate, .(playlistTitle), transform, viewsCumulated = cumsum(totalViews))
p <- ggplot(cumulatedViewsPerDate) + 
  geom_line(aes(date, viewsCumulated, colour=playlistTitle)) + 
  xlab('Date') + ylab('Time [min]') + 
  scale_x_date(breaks = "1 month", minor_breaks = "1 week", labels=date_format("%d %b %Y")) +  
  opts(title = 'Total minutes of watched video', legend.position=c(0.2,0.8))
#p
ggsave("plots/03 Cumulated minutes of watched video.pdf", p, width=10, height=6)

p <- ggplot(cumulatedViewsPerDate) + 
  geom_line(aes(date, viewsCumulated, colour=playlistTitle), alpha=0.5) + 
  geom_line(data=totalViewsPerDate, aes(date, 4*totalViews, colour=playlistTitle), alpha=1.0) + 
  xlab('Date') + ylab('Total time seen [min] or 4 x time seen per day [min]') + 
  scale_x_date(breaks = "1 month", minor_breaks = "1 week", labels=date_format("%d %b %Y")) +
  opts(title = 'Total minutes of watched video', legend.position=c(0.2,0.8)) + 
  scale_colour_discrete(name = "Playlist")
p
ggsave("plots/04 Cumulated minutes of watched video.pdf", p, width=10, height=6)

p <- ggplot(viewsPerDate[viewsPerDate$date < '2013-02-01', ]) + 
  geom_line(aes(date, totalViews), alpha=0.5) + 
  xlab('Date') + ylab('Watched video [min]') + 
  scale_x_date(breaks = "1 month", minor_breaks = "1 week", labels=date_format("%d %b %Y")) +
  opts(title = 'Watched video', legend.position=c(0.2,0.8)) + 
  scale_colour_discrete(name = "Playlist")
p
ggsave("plots/05MinutesWatched.pdf", p, width=10, height=6)
# TODO: Update dates
#examdates <- data.frame(date = as.Date(c('2013-01-04', '2013-01-25', '2013-06-03', '2013-06-25')))
examdates <- data.frame(date = as.Date(c('2013-01-04', '2013-01-25')))
pp <- p + geom_vline(aes(xintercept=as.numeric(date)), examdates, color='red')
ggsave("plots/05MinutesWatchedExamDate.pdf", pp, width=10, height=6)

