library(ggplot2)
library(plyr)

# Load data generated by ../analyticstestingtwo.py
playlistContents <- read.table('../playlists.txt', sep=',', header=T)
titles <- read.table('../videoIdsAndTitles.txt', sep=',')
colnames(titles) <- c('videoId', 'videoTitle')
viewsOfVideo <- read.table('../datesAndViews.txt', sep=',')
colnames(viewsOfVideo) <- c('videoId', 'date', 'views')
viewsOfVideo$date <- as.Date(viewsOfVideo$date)

viewOnPlaylists <- merge(viewsOfVideo, playlistContents, by='videoId')

# Calculate total number of views
totalViewsPerDate <- ddply(viewOnPlaylists, .(date, playlistTitle), summarize, totalViews=sum(views))

# General overview of minutes watched on different playlists.
p <- ggplot(totalViewsPerDate) + 
    geom_line(aes(date, totalViews, colour=playlistTitle)) + 
    xlab('Dato') + ylab('Minutter set')
p

# Specific view of fall semester and IFG1 videos
inFallSemester = subset(totalViewsPerDate, 
                        as.Date(totalViewsPerDate$date) > "2012-09-01" &
                          as.Date(totalViewsPerDate$date) < "2013-01-31")
p <- ggplot(subset(inFallSemester, inFallSemester$playlistTitle == 'IFG1 - Introduktion til Matematik og Fysik')) + 
  geom_line(aes(date, totalViews)) + 
  xlab('Dato') + ylab('Minutter set')
p

ggsave("minutesWatched.pdf", p)



cumulatedViewsPerDate = ddply(totalViewsPerDate, .(playlistTitle), transform, viewsCumulated = cumsum(totalViews))
p <- ggplot(cumulatedViewsPerDate) + 
  geom_line(aes(date, viewsCumulated, colour=playlistTitle)) + 
  xlab('Dato') + ylab('Tid [min]') + 
  opts(title = 'Samlet antal sete videominutter', legend.position=c(0.2,0.8))
p
ggsave("cumulatedVideoMinutesWatched.pdf", p)

