library(ggplot2)
library(plyr)
library(scales)


# Load data generated by ../analyticstestingtwo.py
playlistContents <- read.table('../playlists.txt', sep=',', header=T)
titles <- read.table('../videoIdsAndTitles.txt', sep=',')
colnames(titles) <- c('videoId', 'videoTitle')
viewsOfVideo <- read.table('../datesAndViews.txt', sep=',')

colnames(viewsOfVideo) <- c('videoId', 'date', 'views')
viewsOfVideo$date <- as.Date(viewsOfVideo$date)
viewsOfVideo$year <- substr(viewsOfVideo$date, 1, 4)
viewsOfVideo$month <- substr(viewsOfVideo$date, 6, 7)
viewsOfVideo$day <- substr(viewsOfVideo$date, 9, 10)
viewOnPlaylists <- merge(viewsOfVideo, playlistContents, by='videoId')

# Subset to interesting time period
viewsOfVideo <- subset(viewsOfVideo, viewsOfVideo$date > '2013-08-31')
viewOnPlaylists <- subset(viewOnPlaylists, viewOnPlaylists$date > '2013-08-31')

# Calculate total number of views
totalViewsPerDate <- ddply(viewOnPlaylists, .(date, playlistTitle), summarize, totalViews=sum(views))
viewsPerDate <- ddply(viewOnPlaylists, .(date), summarize, totalViews=sum(views))

# Calculate total number of views per video per month
totalViewsPerVideoPerMonth <- ddply(viewsOfVideo, .(year, month, videoId), summarize, totalViews=sum(views))
titlesViewPerMonth <- merge(totalViewsPerVideoPerMonth, titles, by='videoId')
titlesViewPerMonth$videoTitleShort <- substr(titlesViewPerMonth$videoTitle, 0, 50)
temp <- titlesViewPerMonth[order(-titlesViewPerMonth$totalViews), c('year', 'month', 'totalViews', 'videoTitle', 'videoTitleShort')]
temp[, c('year', 'month', 'totalViews', 'videoTitleShort')]

extractFiveVideosWithMostViews <- function(df)
{
  print(df)
  temp <- df[order(-df$totalViews), c('year', 'month', 'totalViews', 'videoTitleShort')]  
  tempTwo <- head(temp, 5)
  print(tempTwo)
  tempTwo
}
ddply(titlesViewPerMonth, .(year, month), extractFiveVideosWithMostViews)

# General overview of minutes watched on different playlists.
p <- ggplot(totalViewsPerDate) + 
    geom_line(aes(date, totalViews, colour=playlistTitle)) + 
    xlab('Dato') + ylab('Minutter set') +
    scale_x_date(breaks = "1 month", minor_breaks = "1 week", labels=date_format("%d %b %Y"))
ggsave("plots/01 General overview.pdf", p, width=10, height=6)


cumulatedViewsPerDate = ddply(totalViewsPerDate, .(playlistTitle), transform, viewsCumulated = cumsum(totalViews))
p <- ggplot(cumulatedViewsPerDate) + 
  geom_line(aes(date, viewsCumulated, colour=playlistTitle)) + 
  xlab('Date') + ylab('Time [min]') + 
  scale_x_date(breaks = "1 month", minor_breaks = "1 week", labels=date_format("%d %b %Y")) +  
  labs(title = 'Total minutes of watched video') + 
  theme(legend.position=c(0.2,0.8))
ggsave("plots/03 Cumulated minutes of watched video.pdf", p, width=10, height=6)

p <- ggplot(cumulatedViewsPerDate) + 
  geom_line(aes(date, viewsCumulated, colour=playlistTitle), alpha=0.5) + 
  geom_line(data=totalViewsPerDate, aes(date, 4*totalViews, colour=playlistTitle), alpha=1.0) + 
  xlab('Date') + ylab('Total time seen [min] or 4 x time seen per day [min]') + 
  scale_x_date(breaks = "1 month", minor_breaks = "1 week", labels=date_format("%d %b %Y")) +
  scale_colour_discrete(name = "Playlist") +
  labs(title = 'Total minutes of watched video') + 
  theme(legend.position=c(0.2,0.8))
ggsave("plots/04 Cumulated minutes of watched video.pdf", p, width=10, height=6)

